---
title: "01_data"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r git, eval=FALSE}
usethis::create_from_github("https://github.com/Sfglatt/wish-to-live-die-overlap.git",
  destdir = "~/Github/wish-to-live-die-overlap"
)
```

```{r packages}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("tidyr")) {
  install.packages("tidyr")
  require("tidyr")
}
```

# Import dataset
```{r data and dir}
# Import RCT data (from project life force repo)
plf_data <- read.csv("~/Labs/Github/project-life-force/project-life-force/01_Created_datasets/Merged_plf_data_filtered_2025-08-05.csv")

# Filter out month = -9 (lifetime variable)
plf_data <- plf_data %>%
  dplyr::filter(month != -9)

# Make a folder to save the output
if (!dir.exists("01_output")) {
  dir.create("01_output")
}
```

# Dataset for models
```{r dataset}
# People with complete data on all baseline study variables
complete_ids <- plf_data %>%
  filter(month == 0) %>%
  filter(
    !is.na(q01_ssi),
    !is.na(q02_ssi),
    !is.na(bdi),
    !is.na(bhs),
    !is.na(srcs17),
    !is.na(inq_pb),
    !is.na(inq_tb),
    !is.na(rls)
  ) %>%
  pull(id) %>% 
  unique()

# Keep only participants with complete baseline data in the full longitudinal dataset
plf_data_clean <- plf_data %>%
  filter(id %in% complete_ids)

# Restrict to baseline 
plf_data_baseline <- plf_data_clean %>%
  filter(month == 0)
```

# Save dataset
```{r save data}
# Baseline
write.csv(plf_data_baseline,
  file = paste0(
    "01_output/Baseline_data_",
    format(Sys.Date(), "%Y-%m-%d"), ".csv"
  ),
  row.names = TRUE
)

# Full longitudinal
write.csv(plf_data_clean,
  file = paste0(
    "01_output/Temporal_data_",
    format(Sys.Date(), "%Y-%m-%d"), ".csv"
  ),
  row.names = TRUE
)
# Versions
# 12-19-2025: Initial analysis dataset
# 12-24-2025: No change to baseline (initial dataset), added longitudinal dataset
```


